# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapreduce.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\"\x14\n\x04Ping\x12\x0c\n\x04ping\x18\x01 \x01(\x05\"\x14\n\x04Pong\x12\x0c\n\x04pong\x18\x01 \x01(\x05\"\x1e\n\x0bTaskRequest\x12\x0f\n\x07request\x18\x01 \x01(\x05\"l\n\x0eTaskAssignment\x12\x18\n\x10\x61ssignmentStatus\x18\x01 \x01(\x05\x12\x0e\n\x06taskId\x18\x02 \x01(\x05\x12\x10\n\x08taskType\x18\x03 \x01(\x05\x12\x13\n\x0binput_files\x18\x04 \x03(\t\x12\t\n\x01M\x18\x05 \x01(\x05\"2\n\x0eTaskCompletion\x12\x0e\n\x06taskId\x18\x01 \x01(\x05\x12\x10\n\x08taskType\x18\x02 \x01(\x05\"5\n\x11TaskCompletionACK\x12\x0e\n\x06taskId\x18\x01 \x01(\x05\x12\x10\n\x08taskType\x18\x02 \x01(\x05\x32\x97\x01\n\x06\x44river\x12\x1a\n\x08PingPong\x12\x05.Ping\x1a\x05.Pong\"\x00\x12-\n\nAssignTask\x12\x0c.TaskRequest\x1a\x0f.TaskAssignment\"\x00\x12\x42\n\x19\x41\x63knowledgeTaskCompletion\x12\x0f.TaskCompletion\x1a\x12.TaskCompletionACK\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PING']._serialized_start=19
  _globals['_PING']._serialized_end=39
  _globals['_PONG']._serialized_start=41
  _globals['_PONG']._serialized_end=61
  _globals['_TASKREQUEST']._serialized_start=63
  _globals['_TASKREQUEST']._serialized_end=93
  _globals['_TASKASSIGNMENT']._serialized_start=95
  _globals['_TASKASSIGNMENT']._serialized_end=203
  _globals['_TASKCOMPLETION']._serialized_start=205
  _globals['_TASKCOMPLETION']._serialized_end=255
  _globals['_TASKCOMPLETIONACK']._serialized_start=257
  _globals['_TASKCOMPLETIONACK']._serialized_end=310
  _globals['_DRIVER']._serialized_start=313
  _globals['_DRIVER']._serialized_end=464
# @@protoc_insertion_point(module_scope)
